# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_auto_20170122_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='representative',
            name='comp_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenario.CompPlan'),
        ),
    ]
