# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_auto_20170125_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attainment_tier', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('payout_tier', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('comp_plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenario.CompPlan')),
            ],
        ),
    ]
