# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_tiers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiers',
            new_name='Tier',
        ),
    ]
