# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_auto_20170125_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='tier_number',
            field=models.IntegerField(default=1),
        ),
    ]
